routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['role:admin', 'auth']], function(){
    Route::get('', 'HomeController@index')->name('admin.index');
    Route::resource('books', 'BookController', [
        'as' => 'admin',
    ]);
    Route::post('add-list-book', 'BookController@addList')->name('admin.books.import');
    Route::get('add-list-book', 'BookController@showAddList')->name('admin.books.addlist');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'User\HomeController@index')->name('home.index');

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    /**
     * The table associated with the model.
     * @var string
     */
    protected $table = 'books';

    /**
     * The attributes that are mass assignable.
     * @var array
     */
    protected $fillable = [
        'name',
        'type',
        'des',
        'url',
        'page',
        'views',
        'created_by',
        'updated_by',
    ];

    public function users() {
        return $this->belongsToMany(User::class)->withTimestamps();
    }

    public function rates()
    {
        return $this->morphMany('App\Models\Rate', 'ratable');
    }

    public function comments()
    {
        return $this->morphMany('App\Models\Comment', 'commentable');
    }
}

app/Http/Controllers/Admin/BookController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Exceptions\NotFoundException;
use App\Http\Controllers\Controller;
use App\Imports\BooksImport;
use App\Repositories\Book\BookRepositoryInterface;
use App\Repositories\User\UserRepositoryInterface;
use App\Http\Requests\BookRequest;
use Illuminate\Http\UploadedFile;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Redirect;
use Maatwebsite\Excel\Facades\Excel;
use ZipArchive;

class BookController extends Controller
{
    protected $bookRepository;
    protected $userRepository;

    public function __construct(BookRepositoryInterface $bookRepository, UserRepositoryInterface $userRepository)
    {
        $this->bookRepository = $bookRepository;
        $this->userRepository = $userRepository;
    }

    public function index()
    {
        $books = $this->bookRepository->getListBook();
        return view('admin.books.index', compact('books'));
    }

    public function create()
    {
        return view('admin.books.create');
    }

    public function store(BookRequest $request)
    {
        $file = $request->file('url');
        $url = $file->getClientOriginalName();
        $this->saveFile($file);
        $book = array(
            'name' => $request->get('name'),
            'type' => $request->get('type'),
            'des' => $request->get('des'),
            'url' => $url,
            'page' => $this->getTotalPages($file),
            'views' => 0,
        );
        $this->bookRepository->create($book);

        return redirect()->route('admin.books.index');
    }

    public function show($id)
    {
        try {
            $book = $this->bookRepository->find($id);
        } catch (NotFoundException $exception) {
            throw $exception;
        }
        $created_by = $this->userRepository->getModelById($book->created_by)->name ?? 'unidentified user';
        $updated_by = $this->userRepository->getModelById($book->updated_by)->name ?? 'unidentified user';

        return view('admin.books.detail', [
            'book' => $book,
            'created_by' => $created_by,
            'updated_by' => $updated_by,
        ]);
    }

    public function edit($id)
    {
        try {
            $book = $this->bookRepository->find($id);
        } catch (NotFoundException $exception) {
            throw $exception;
        }

        return view('admin.books.edit', compact('book'));
    }

    public function update(BookRequest $request, $id)
    {
        $book = $this->bookRepository->getModelById($id);
        $attribute = $request->all();
        if ($request->hasFile('url'))
        {
            $file = $request->file('url');
            $url = $file->getClientOriginalName();
            $this->saveFile($file);
            $attribute = array_merge($attribute, array(
                'url' => $url,
                'page' => $this->getTotalPages($file),
            ));
        }
        $book->update($attribute);

        return redirect()->route('admin.books.index');
    }

    public function saveFile(UploadedFile $file)
    {
        $filename = $file->getClientOriginalName();
        $file->storeAs('public/pdf', $filename);
    }

    public function getTotalPages($file)
    {
        $pdftext = file_get_contents($file);
        $page = preg_match_all("/\/Page\W/", $pdftext, $dummy);

        return $page;
    }

    public function destroy($id)
    {
        try {
            $book = $this->bookRepository->find($id);
        } catch (NotFoundException $exception) {
            throw $exception;
        }
        $book->delete($id);

        return response()->json("success", 200);
    }

    public function addList(Request $request)
    {
        $filezip = $request->file('file');
        if ($this->exactFile($filezip))
        {
            $unzipfile = substr($filezip->getClientOriginalName(), 0, -4);
            $path = storage_path('app/public/zip/'.$unzipfile);
            $files = File::allFiles($path);
            $listpdfs = array();
            $filexlsx = new File;
            foreach ($files as $file)
            {
                if ($file->getExtension() == 'pdf')
                {
                    $page = $this->getTotalPages($file);
                    $pdf = array(
                        $file->getFilename() => $page,
                    );
                    $listpdfs = array_merge($listpdfs, $pdf);
                    File::copy($path.'/'.$file->getFilename(), storage_path('app/public/pdf/'.$file->getFilename()));
                } elseif ($file->getExtension() == 'xlsx') {
                    $filexlsx = $file;
                }
            }
            $pathxlsx = $path.'/'.$filexlsx->getFilename();
            $this->import($pathxlsx, $listpdfs);
        } else {
            return Redirect::back()->withErrors(['File open failed!']);
        }

        return redirect()->route('admin.books.index');
    }

    public function import($filepath, $listpdf)
    {
        $import = new BooksImport($listpdf);
        Excel::import($import, $filepath);
    }

    public function exactFile(UploadedFile $file)
    {
        $filename = $file->getClientOriginalName();
        $ext = pathinfo($filename, PATHINFO_EXTENSION);
        $valid_ext = array('zip');
        if(in_array(strtolower($ext),$valid_ext)){
            $tmp_name = $file->getPathname();
            $zip = new ZipArchive;
            $res = $zip->open($tmp_name);
            if ($res === TRUE) {
                $path = storage_path('app/public/zip');
                $zip->extractTo($path);
                $zip->close();
                return true;
            } else {
                return false;
            }
        }else{
            return false;
        }
    }

    public function showAddList(Request $request)
    {
        return view('admin.books.addlist');
    }
}

resources/views/admin/books/addlist.blade.php
@extends('admin.layouts.master')

@section('content')
    <div>
        @if($errors->any())
            <h4 style="color: red">{{$errors->first()}}</h4>
        @endif
        <form method='post' action='' enctype='multipart/form-data'>
            @csrf
            <label for="url">File upload (.zip):</label>
            <input type='file' name='file'><br/>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/admin/books/create.blade.php
@extends('admin.layouts.master')

@section('content')
    <div id="content-wrapper">
        <div class="container col-md-6">
            <form action={{ route('admin.books.store') }} method="POST" enctype="multipart/form-data">
                @method('post')
                @csrf
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}" required>
                    @error('name')
                    <div class="has-feedback text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="type">Type:</label>
                    <input type="text" class="form-control" id="type" name="type" value="{{ old('type') }}" required>
                    @error('type')
                    <div class="has-feedback text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="des">Description:</label>
                    <input type="text" class="form-control" id="des" name="des" value="{{ old('des') }}" required>
                    @error('des')
                    <div class="has-feedback text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group" >
                    <label for="url">File pdf:</label>
                    <input type="file" name="url" multiple="multiple" required>
                    @error('url')
                    <div class="has-feedback text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/books/detail.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-6" style="background: #4dc0b5">
                <iframe src="{{ asset('storage/pdf/'.$book->url) }}" title="{{ $book->name }}" width="100%" height="600"></iframe>
            </div>
            <div class="col-6 bg-info">
                <br>
                <h4 style="color: #0D3349">Id: {{ $book->id }}</h4>
                <h4 style="color: #0D3349">Name: {{ $book->name }}</h4>
                <h4 style="color: #0D3349">Type: {{ $book->type }}</h4>
                <h4 style="color: #0D3349">Description: {{ $book->des }}</h4>
                <h4 style="color: #0D3349">Number of page: {{ $book->page }}</h4>
                <h4 style="color: #0D3349">Views: {{ $book->views }}</h4>
                <h4 style="color: #0D3349">Admin created: {{ $created_by }} in {{ $book->created_at }}</h4>
                <h4 style="color: #0D3349">Admin updated: {{ $updated_by }} in {{ $book->updated_at }}</h4>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/books/edit.blade.php
@extends('admin.layouts.master')

@section('content')
    <div id="content-wrapper">
        <div class="container col-md-6">
            <form action="{{ route('admin.books.update', $book->id) }}" method="POST" enctype="multipart/form-data">
                @method('put')
                @csrf
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" id="name" name="name" value="{{ $book->name }}" required>
                    @error('name')
                    <div class="has-feedback text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="type">Type:</label>
                    <input type="text" class="form-control" id="type" name="type" value="{{ $book->type }}" required>
                    @error('type')
                    <div class="has-feedback text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="des">Description:</label>
                    <input type="text" class="form-control" id="des" name="des" value="{{ $book->des }}" required>
                    @error('des')
                    <div class="has-feedback text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group" >
                    <label for="url">File pdf:</label>
                    <iframe src="{{ asset('storage/pdf/'.$book->url) }}" title="{{ $book->name }}" width="100%" height="600"></iframe>
                    <input type="file" name="url" value="{{ $book->url }}">
                    @error('url')
                    <div class="has-feedback text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/books/index.blade.php
@extends('admin.layouts.master')

@section('content')
    <div>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Type</th>
                <th scope="col">Description</th>
                <th scope="col">Url</th>
                <th scope="col">Page</th>
                <th scope="col">Views</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
            </thead>
            <tbody>
            @foreach($books as $book)
                <tr>
                    <th scope="row">{{ $book->id }}</th>
                    <td>
                        <a href="{{ route('admin.books.show', $book->id)  }}">
                            {{ $book->name }}
                        </a></td>
                    <td>{{ $book->type }}</td>
                    <td>{{ $book->des }}</td>
                    <td>
                        <a href="{{ asset('storage/pdf/'.$book->url) }}">{{ $book->url }}</a>
                    </td>
                    <td>{{ $book->page }}</td>
                    <td>{{ $book->views }}</td>
                    <td>
                        <button type="button" class="btn btn-primary">
                            <a href="{{ route('admin.books.edit', $book->id) }}" style="color: white">Edit</a>
                        </button>
                    </td>
                    <td>
                        <button class="btn btn-danger delete-book" data-id="{{ $book->id }}" type="button">
                            Delete
                        </button>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

@push('js')
<script src="{{ asset('js/deletebook.js') }}"></script>
@endpush