routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['role:admin', 'auth']], function(){
    Route::get('', 'HomeController@index')->name('admin.index');
    Route::resource('books', 'BookController', [
        'as' => 'admin',
    ]);
    Route::post('add-list-book', 'BookController@addList')->name('admin.books.import');
    Route::get('add-list-book', 'BookController@showAddList')->name('admin.books.addlist');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'User\HomeController@index')->name('home.index');

resources/views/admin/layouts/footer.blade.php
<?php

resources/views/admin/layouts/header.blade.php
<!-- Header -->
<header>
    <div class="container-fluid">
        <div class="row">
            <div class="col-2 bg-light">
                <a href="{{ route('admin.index') }}" title="The Book Station: Free for everyone">
                    <div>
                        <img src="{{ asset('storage/images/logo.png') }}">
                    </div>
                </a>
            </div>
            <div class="col-8 bg-info">
                <h2 style="color: whitesmoke; text-align: center">
                    Book Station's Manager Homepage
                </h2>
            </div>
            <div class="col-2 bg-light">
                <nav class="navbar navbar-expand-sm">
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="btn btn-info" role="button" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>

resources/views/admin/layouts/master.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">

    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@lang('view.title')</title>

    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

    <link rel="stylesheet" href="{{ asset('bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('bower_components/bootstrap-sweetalert/dist/sweetalert.css') }}">

    <script src="{{ asset('bower_components/jquery/dist/jquery.min.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="{{ asset('bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('bower_components/bootstrap-sweetalert/dist/sweetalert.min.js') }}"></script>
    <script src="{{ asset('bower_components/bootstrap-sweetalert/dist/sweetalert.js') }}"></script>
    @stack('js')
</head>
<body class="cms-index-index cms-home-page">
@include('admin.layouts.header')
<br>
<div class="container-fluid">
    <div class="row">
        <div class="col-2" style="background: whitesmoke">
            @include('admin.layouts.sidebar')
        </div>
        <div class="col-10 bg-light">
            <div>
                @yield('content')
            </div>
        </div>
    </div>
</div>
@include('admin.layouts.footer')
</body>
</html>

resources/views/admin/layouts/sidebar.blade.php
<br>
<div class="btn-group dropright" style="display: list-item">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Manage Book
    </button>
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{{ route('admin.books.index') }}">List books</a>
        <a class="dropdown-item" href="{{ route('admin.books.create') }}">Add book</a>
        <a class="dropdown-item" href="{{ route('admin.books.addlist') }}">Add list book</a>
    </div>
</div>